#!/usr/bin/env bash
# Bundles the migrations production does not have yet into ONE transaction for
# the Supabase dashboard SQL editor — the only route in from a network where the
# Postgres ports are firewalled (the office). `supabase db push` from a phone
# hotspot is the preferred route; this is the fallback.
#
# Usage, from the repo root:
#   bash scripts/cutover/build-consolidated.sh 0015 0016
#   bash scripts/cutover/build-consolidated.sh            # defaults to PENDING below
#
# Writes scripts/cutover/cutover_consolidated.sql. The migration-history rows at
# the end are DERIVED from every file in supabase/migrations (idempotent inserts),
# so a later `db push` sees them all as applied instead of re-running them.
set -euo pipefail
cd "$(dirname "$0")/../.."

PENDING=("$@")
if [ ${#PENDING[@]} -eq 0 ]; then PENDING=(0015 0016); fi

OUT="scripts/cutover/cutover_consolidated.sql"

# Anything that cannot run inside a transaction would silently break the
# all-or-nothing guarantee the header promises.
if grep -rin "concurrently\|alter system\|create database" supabase/migrations/ >/dev/null; then
  echo "refusing: a migration contains a statement that cannot run in a transaction" >&2
  exit 1
fi

{
  cat <<'HEADER'
-- ===========================================================================
-- Shut the Box — pending migrations, as one transaction.
--
-- For the Supabase dashboard SQL editor (Dashboard → SQL Editor → New query →
-- paste → Run). GENERATED by scripts/cutover/build-consolidated.sh from
-- supabase/migrations/ — do not hand-edit; regenerate instead.
--
-- One transaction: if anything fails, NOTHING is applied and the database is
-- exactly as it was. Re-running after a success fails on the first statement
-- (the objects already exist), which is also safe and means nothing happened.
--
-- Ends by recording every migration file as applied in the CLI's history
-- table, so a later `supabase db push` from an unblocked network agrees with
-- what is actually in the database.
-- ===========================================================================

begin;

create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version    text not null primary key,
  statements text[],
  name       text
);
HEADER

  echo
  echo "-- Applying: ${PENDING[*]}"
  for v in "${PENDING[@]}"; do
    f=$(ls supabase/migrations/"${v}"_*.sql)
    printf '\n\n-- ======================= %s =======================\n\n' "$(basename "$f")"
    cat "$f"
  done

  cat <<'FOOTER'


-- ===========================================================================
-- Migration history: every file in supabase/migrations, recorded as applied.
-- Earlier ones were applied by hand or by db push; the ones above just ran.
-- ===========================================================================
insert into supabase_migrations.schema_migrations (version, name)
values
FOOTER
  first=1
  for f in supabase/migrations/[0-9]*_*.sql; do
    b=$(basename "$f" .sql)
    v=${b%%_*}
    n=${b#*_}
    if [ $first -eq 1 ]; then first=0; else echo ","; fi
    printf "  ('%s', '%s')" "$v" "$n"
  done
  echo
  echo "on conflict (version) do nothing;"
  echo
  echo "commit;"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes) applying: ${PENDING[*]}"
