-- ===========================================================================
-- Shut the Box — pending migrations, as one transaction.
--
-- For the Supabase dashboard SQL editor (Dashboard → SQL Editor → New query →
-- paste → Run). GENERATED by scripts/cutover/build-consolidated.sh from
-- supabase/migrations/ — do not hand-edit; regenerate instead.
--
-- One transaction: if anything fails, NOTHING is applied and the database is
-- exactly as it was. Re-running after a success fails on the first statement
-- (the objects already exist), which is also safe and means nothing happened.
--
-- Ends by recording every migration file as applied in the CLI's history
-- table, so a later `supabase db push` from an unblocked network agrees with
-- what is actually in the database.
-- ===========================================================================

begin;

create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version    text not null primary key,
  statements text[],
  name       text
);

-- Applying: 0024


-- ======================= 0024_two_kickoff_times.sql =======================

-- Shut the Box — the match moves to 14:00 on Wednesday to Friday.
--
-- Gustav, 2026-10-07: Monday and Tuesday stay at 12:45, Wednesday to Friday
-- play at 14:00. The "Snart match!" reminder goes out five minutes before
-- either, so the single weekday job from 0020 splits in two. Same daylight-
-- saving trick as 0020: each job sits at both UTC hours that can map to its
-- Stockholm time, and run_scheduled_job keeps the one whose local hour
-- matches.
--
--   Mon–Tue 12:40 Stockholm = 10:40 UTC in summer, 11:40 UTC in winter
--   Wed–Fri 13:55 Stockholm = 11:55 UTC in summer, 12:55 UTC in winter
--
-- Both jobs call the same endpoint, and the card works out 12:45 or 14:00
-- from the date (kickoffTime in teams-cards.ts). The weekday split therefore
-- lives in two places: change one, change both. cron_runs still allows one
-- 'prematch' per day, and only one of the two jobs fires on any given day.

select cron.unschedule(jobid)
  from cron.job
 where jobname in ('stb_prematch', 'stb_prematch_late');

select cron.schedule(
  'stb_prematch',
  '40 10,11 * * 1-2',
  $$select run_scheduled_job('/api/cron/prematch', 12)$$
);

select cron.schedule(
  'stb_prematch_late',
  '55 11,12 * * 3-5',
  $$select run_scheduled_job('/api/cron/prematch', 13)$$
);


-- ===========================================================================
-- Migration history: every file in supabase/migrations, recorded as applied.
-- Earlier ones were applied by hand or by db push; the ones above just ran.
-- ===========================================================================
insert into supabase_migrations.schema_migrations (version, name)
values
  ('0001', 'tables'),
  ('0002', 'views'),
  ('0003', 'lock_12_tile'),
  ('0004', 'rulesets_seasons'),
  ('0005', 'game_lifecycle'),
  ('0006', 'audit_identity_audio'),
  ('0007', 'views'),
  ('0008', 'ratings'),
  ('0009', 'achievements'),
  ('0010', 'rpc_game_flow'),
  ('0011', 'realtime'),
  ('0012', 'finish_game_settles'),
  ('0013', 'game_management'),
  ('0014', 'plan_season'),
  ('0015', 'storage'),
  ('0016', 'safeupdate'),
  ('0017', 'roster'),
  ('0018', 'fika'),
  ('0019', 'cron'),
  ('0020', 'schedule'),
  ('0021', 'tournament'),
  ('0022', 'fika_avg_finish'),
  ('0023', 'one_counted_game_per_day'),
  ('0024', 'two_kickoff_times')
on conflict (version) do nothing;

commit;
