-- ===========================================================================
-- Shut the Box — pending migrations, as one transaction.
--
-- For the Supabase dashboard SQL editor (Dashboard → SQL Editor → New query →
-- paste → Run). GENERATED by scripts/cutover/build-consolidated.sh from
-- supabase/migrations/ — do not hand-edit; regenerate instead.
--
-- One transaction: if anything fails, NOTHING is applied and the database is
-- exactly as it was. Re-running after a success fails on the first statement
-- (the objects already exist), which is also safe and means nothing happened.
--
-- Ends by recording every migration file as applied in the CLI's history
-- table, so a later `supabase db push` from an unblocked network agrees with
-- what is actually in the database.
-- ===========================================================================

begin;

create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version    text not null primary key,
  statements text[],
  name       text
);

-- Applying: 0023


-- ======================= 0023_one_counted_game_per_day.sql =======================

-- Shut the Box — a shut box no longer ends the game, and a day has one game.
--
-- On 2026-10-01 and 2026-10-05 somebody shut the box on the second turn. The
-- house ruleset said that ended the game on the spot, so everyone after her
-- was marked dnp — and the rest of the table, quite reasonably, played another
-- game, which then counted as a win, a rating change and a "vann dagens" card
-- of its own. The rules agreed on 2026-10-05:
--
--   * everybody plays their turn, and a zero simply wins (two zeros share it,
--     as any tie does);
--   * one game counts per day. A counted game is a finished one that has not
--     been deleted; an abandoned game never counted and still does not. Team
--     play keeps its own tables and is untouched.
--
-- See docs/adr/0001-one-counted-game-per-day.md for why the database enforces
-- the second rule rather than leaving it to the app.
--
-- Also here, because it ships with the same release: player_recent_form, each
-- player's last five games, for the reworked Players overview.
--
-- Additional error codes: STB13 that day already has its game (detail: the id
-- of that game); STB14 a game is already being played that day (detail: the id
-- of the live game).

-- ---------------------------------------------------------------------------
-- Pre-flight: no day may already hold two counted games
-- ---------------------------------------------------------------------------

-- The unique index below would refuse with a bare "could not create unique
-- index". Production had three such days (2026-09-09, 2026-10-01, 2026-10-05);
-- they are merged by a script that has to run first.
do $preflight$
declare
  v_days text;
begin
  select string_agg(played_on::text, ', ' order by played_on) into v_days
    from (select played_on from games
           where status = 'finished' and deleted_at is null
           group by played_on having count(*) > 1) d;
  if v_days is not null then
    raise exception 'one counted game per day: % still hold more than one — run scripts/fixes/2026-10-05-merge-split-days.sql first', v_days;
  end if;
end
$preflight$;

-- ---------------------------------------------------------------------------
-- The rule itself
-- ---------------------------------------------------------------------------

-- In place, on every seeded ruleset. Games point at their ruleset rather than
-- copying it, so this applies to the game in progress as well as the next one;
-- nothing derived (scores, ratings, badges) ever read the setting, and old dnp
-- rows stay exactly as they were played. The setting itself stays in the rules
-- schema, so a seasonal ruleset could still turn it back on.
update rulesets
   set rules = jsonb_set(rules, '{shut_box,instant_win}', 'false'::jsonb)
 where slug in ('vanilla-12', 'call-your-shot-12', 'digital-9');

-- ---------------------------------------------------------------------------
-- Correcting a turn hands turns back only to players who were skipped
-- ---------------------------------------------------------------------------

-- Replaces 0010. The block that gives skipped players their turns back ran
-- whenever no board was empty, even when nobody had been skipped. Harmless
-- while every shut box ended the game, but with play continuing it would put
-- the next waiting player up while someone was already rolling: two players
-- 'playing', and the live board pointed at the wrong one.
create or replace function set_turn_result(
  p_actor      uuid,
  p_game_id    uuid,
  p_player_id  uuid,
  p_tiles_open smallint[],
  p_score      integer,
  p_predicted  integer default null
) returns jsonb language plpgsql volatile as $fn$
declare
  v_rules jsonb := assert_scorekeeper(p_actor, p_game_id);
  v_first uuid;
begin
  update game_players
     set status          = 'done',
         score           = p_score,
         tiles_open      = p_tiles_open,
         predicted_score = p_predicted
   where game_id = p_game_id and player_id = p_player_id;
  if not found then
    raise exception 'that player is not in this game' using errcode = 'STB04';
  end if;

  -- If the correction means nobody shut the box after all, the players who were
  -- skipped are owed their turn back.
  if exists (
    select 1 from game_players
     where game_id = p_game_id and status = 'dnp'
  ) and not exists (
    select 1 from game_players
     where game_id = p_game_id
       and status = 'done'
       and coalesce(cardinality(tiles_open) = 0, false)
  ) then
    update game_players set status = 'pending'
     where game_id = p_game_id and status = 'dnp';

    select player_id into v_first
      from game_players
     where game_id = p_game_id and status = 'pending'
     order by turn_order
     limit 1;

    if v_first is not null then
      update game_players set status = 'playing'
       where game_id = p_game_id and player_id = v_first;
      update live_turns
         set player_id  = v_first,
             tiles_down = '{}',
             version    = version + 1
       where game_id = p_game_id;
    end if;
  end if;

  update live_turns set version = version + 1 where game_id = p_game_id;
  return live_game_snapshot(p_game_id);
end
$fn$;

-- ---------------------------------------------------------------------------
-- An edit keeps a shut box's empty board
-- ---------------------------------------------------------------------------

-- Replaces 0013. array_agg over zero elements is NULL, not '{}', so every edit,
-- undo and after-the-fact entry turned a shut box's empty board into "no board
-- recorded". is_shut_box still came out right through its score = 0 fallback,
-- which is why nobody noticed; the board itself was lost. The order of the
-- tiles is kept as given, too.
create or replace function apply_game_results(
  p_game_id uuid,
  p_results jsonb
) returns void language plpgsql volatile as $fn$
declare
  v_row   jsonb;
  v_order integer := 0;
  v_done  integer := 0;
begin
  if p_results is null or jsonb_typeof(p_results) <> 'array'
     or jsonb_array_length(p_results) = 0 then
    raise exception 'a game needs at least one player' using errcode = 'STB02';
  end if;

  delete from game_players where game_id = p_game_id;

  for v_row in select value from jsonb_array_elements(p_results) loop
    v_order := v_order + 1;
    insert into game_players (game_id, player_id, turn_order, status,
                              score, tiles_open, predicted_score)
    values (
      p_game_id,
      (v_row->>'player_id')::uuid,
      v_order,
      coalesce((v_row->>'status')::game_player_status, 'done'),
      case when v_row->>'score' is null then null
           else (v_row->>'score')::integer end,
      case when v_row->>'tiles_open' is null then null
           else coalesce(
             (select array_agg(t::smallint order by o)
                from jsonb_array_elements_text(v_row->'tiles_open')
                     with ordinality e(t, o)),
             '{}'::smallint[]) end,
      case when v_row->>'predicted_score' is null then null
           else (v_row->>'predicted_score')::integer end
    );
  end loop;

  select count(*) into v_done
    from game_players where game_id = p_game_id and status = 'done';
  if v_done = 0 then
    raise exception 'somebody has to have played' using errcode = 'STB02';
  end if;
end
$fn$;

-- ===========================================================================
-- One counted game per day
-- ===========================================================================

-- The same rows games_valid_idx indexed, now unique on the day. Every way a
-- game becomes counted is a write to `games` itself — finish_game sets the
-- status, add_manual_game inserts a finished row, an edit or an undo moves the
-- date, a restore or an undo clears deleted_at — so the index sees all of
-- them, including the one race the checks below cannot close: two phones
-- crowning two games in the same second. The second commit gets 23505 naming
-- this index.
drop index if exists games_valid_idx;
create unique index games_one_counted_per_day on games (played_on)
  where status = 'finished' and deleted_at is null;

-- The friendly version of the index, called before any write so the refusal
-- says which game holds the day. `p_except` is the game being written itself.
-- With `p_check_live`, a game still being played that day blocks too: it is the
-- day's game in the making, and the answer is to watch it or take it over.
create or replace function assert_day_free(
  p_day        date,
  p_except     uuid default null,
  p_check_live boolean default false
) returns void language plpgsql stable as $fn$
declare
  v_id uuid;
begin
  select id into v_id
    from games
   where played_on = p_day
     and status = 'finished'
     and deleted_at is null
     and id is distinct from p_except
   limit 1;
  if v_id is not null then
    raise exception 'that day already has its game'
      using errcode = 'STB13', detail = v_id::text;
  end if;

  if p_check_live then
    select id into v_id
      from games
     where played_on = p_day
       and status = 'in_progress'
       and deleted_at is null
       and id is distinct from p_except
     order by started_at
     limit 1;
    if v_id is not null then
      raise exception 'a game is already being played that day'
        using errcode = 'STB14', detail = v_id::text;
    end if;
  end if;
end
$fn$;

-- ---------------------------------------------------------------------------
-- Starting: replaces 0010
-- ---------------------------------------------------------------------------

create or replace function start_game(p_actor uuid, p_player_ids uuid[])
returns jsonb language plpgsql volatile as $fn$
declare
  v_game_id uuid;
  v_season  uuid;
  v_first   uuid;
begin
  if p_player_ids is null or cardinality(p_player_ids) = 0 then
    raise exception 'nobody is playing' using errcode = 'STB02';
  end if;
  if cardinality(p_player_ids) <> (
       select count(distinct x) from unnest(p_player_ids) x) then
    raise exception 'a player appears twice' using errcode = 'STB02';
  end if;
  if exists (
    select 1 from unnest(p_player_ids) x
     where not exists (select 1 from players p where p.id = x and p.is_active)
  ) then
    raise exception 'that player is not on the active roster'
      using errcode = 'STB02';
  end if;

  -- One live game per scorekeeper. This is the duplicate-game race from v1:
  -- two colleagues both saw "no game yet today" and both saved one.
  if exists (
    select 1 from games
     where scorekeeper_player_id = p_actor
       and status = 'in_progress'
       and deleted_at is null
  ) then
    raise exception 'you are already keeping score for a game'
      using errcode = 'STB09';
  end if;

  -- One game a day: this one, or the one already under way. Two phones
  -- pressing Start in the same second queue on this lock, and the second then
  -- sees the first one's game.
  perform pg_advisory_xact_lock(hashtextextended('stb.start.' || stockholm_today(), 0));
  perform assert_day_free(stockholm_today(), null, true);

  v_season := ensure_season(stockholm_today());
  v_first  := p_player_ids[1];

  insert into games (played_on, ruleset_id, season_id, status,
                     scorekeeper_player_id, created_by)
  select stockholm_today(),
         s.ruleset_id,      -- the season's ruleset, snapshotted onto the game
         s.id,
         'in_progress',
         p_actor,
         p_actor
    from seasons s where s.id = v_season
  returning id into v_game_id;

  insert into game_players (game_id, player_id, turn_order, status)
  select v_game_id, x.id, x.ord,
         case when x.ord = 1 then 'playing' else 'pending' end::game_player_status
    from unnest(p_player_ids) with ordinality as x(id, ord);

  insert into live_turns (game_id, player_id) values (v_game_id, v_first);

  insert into audit_log (actor_player_id, action, entity, entity_id, after)
  values (p_actor, 'game.start', 'game', v_game_id,
          game_snapshot(v_game_id));

  return live_game_snapshot(v_game_id);
end
$fn$;

-- ---------------------------------------------------------------------------
-- Crowning: replaces 0012
-- ---------------------------------------------------------------------------

create or replace function finish_game(p_actor uuid, p_game_id uuid)
returns jsonb language plpgsql volatile as $fn$
declare
  v_game   games;
  v_done   integer;
  v_left   integer;
  v_before jsonb;
  v_new    jsonb;
begin
  select * into v_game from games where id = p_game_id for update;
  if not found or v_game.deleted_at is not null then
    raise exception 'no such game' using errcode = 'STB03';
  end if;
  if v_game.status <> 'in_progress' then
    raise exception 'this game is not in progress' using errcode = 'STB03';
  end if;

  select count(*) filter (where status = 'done'),
         count(*) filter (where status in ('pending', 'playing'))
    into v_done, v_left
    from game_players where game_id = p_game_id;

  if v_left > 0 then
    raise exception 'somebody still has a turn to play' using errcode = 'STB03';
  end if;
  if v_done = 0 then
    raise exception 'nobody has played yet' using errcode = 'STB05';
  end if;

  -- Only reachable when two games were live on one day — a race at the start,
  -- or a game begun before 0023. The one crowned first is the day's game; this
  -- one is left in progress, untouched, for its scorekeeper to abandon.
  perform assert_day_free(v_game.played_on, p_game_id);

  -- What the players in this game already had, so the difference afterwards is
  -- what they just earned.
  select coalesce(jsonb_agg(distinct pa.player_id::text || '|' || pa.achievement_key), '[]'::jsonb)
    into v_before
    from player_achievements pa
   where pa.player_id in (
     select player_id from game_players where game_id = p_game_id
   );

  update games
     set status      = 'finished',
         finished_at = now()
   where id = p_game_id;

  delete from live_turns where game_id = p_game_id;

  -- Both rebuild from the game history, so they have to run after the game
  -- counts as finished.
  perform recompute_ratings();
  perform evaluate_achievements();

  select coalesce(jsonb_agg(jsonb_build_object(
           'player_id', pa.player_id,
           'key', pa.achievement_key,
           'name', a.name,
           'emoji', a.emoji,
           'description', a.description)), '[]'::jsonb)
    into v_new
    from player_achievements pa
    join achievements a on a.key = pa.achievement_key
   where pa.player_id in (
     select player_id from game_players where game_id = p_game_id
   )
     and not (v_before ? (pa.player_id::text || '|' || pa.achievement_key));

  insert into audit_log (actor_player_id, action, entity, entity_id, after)
  values (p_actor, 'game.finish', 'game', p_game_id, game_snapshot(p_game_id));

  return jsonb_build_object('game_id', p_game_id, 'new_achievements', v_new);
end
$fn$;

-- ---------------------------------------------------------------------------
-- Correcting the record: replaces 0013
-- ---------------------------------------------------------------------------

create or replace function edit_game(
  p_actor    uuid,
  p_game_id  uuid,
  p_played_on date,
  p_results  jsonb,
  p_note     text default null
) returns void language plpgsql volatile as $fn$
declare
  v_game   games;
  v_before jsonb;
begin
  select * into v_game from games where id = p_game_id for update;
  if not found then
    raise exception 'no such game' using errcode = 'STB03';
  end if;
  if v_game.status <> 'finished' then
    raise exception 'only a finished game can be edited' using errcode = 'STB03';
  end if;
  if p_played_on > stockholm_today() then
    raise exception 'that date has not happened yet' using errcode = 'STB06';
  end if;
  -- Correcting the scores on the game's own day is never blocked; moving a
  -- counted game onto a day that already has one is.
  if p_played_on is distinct from v_game.played_on and v_game.deleted_at is null then
    perform assert_day_free(p_played_on, p_game_id);
  end if;

  v_before := game_snapshot(p_game_id);

  -- The season follows the date, so moving a game into another quarter moves
  -- it in the standings too. The RULESET does not move: the game was played
  -- under the rules it was played under.
  update games
     set played_on = p_played_on,
         season_id = ensure_season(p_played_on)
   where id = p_game_id;

  perform apply_game_results(p_game_id, p_results);
  perform resettle_history();

  insert into audit_log (actor_player_id, action, entity, entity_id,
                         before, after, note)
  values (p_actor, 'game.edit', 'game', p_game_id,
          v_before, game_snapshot(p_game_id), p_note);
end
$fn$;

create or replace function restore_game(p_actor uuid, p_game_id uuid)
returns void language plpgsql volatile as $fn$
declare
  v_game games;
begin
  select * into v_game from games where id = p_game_id for update;
  if not found or v_game.deleted_at is null then
    return;   -- not deleted; nothing to restore
  end if;
  -- A deleted game whose day has since been played again stays deleted:
  -- bringing it back would make two games count.
  if v_game.status = 'finished' then
    perform assert_day_free(v_game.played_on, p_game_id);
  end if;

  update games set deleted_at = null where id = p_game_id;
  perform resettle_history();

  insert into audit_log (actor_player_id, action, entity, entity_id, after)
  values (p_actor, 'game.restore', 'game', p_game_id,
          game_snapshot(p_game_id));
end
$fn$;

-- Reverses one recorded change, and only if nothing has happened to the game
-- since. Undoing out of order would silently discard whatever came after it.
create or replace function undo_game_change(p_actor uuid, p_audit_id bigint)
returns void language plpgsql volatile as $fn$
declare
  v_entry  audit_log;
  v_latest bigint;
  v_game   games;
  v_day    date;
begin
  select * into v_entry from audit_log where id = p_audit_id;
  if not found or v_entry.entity <> 'game' or v_entry.entity_id is null then
    raise exception 'that change cannot be undone' using errcode = 'STB07';
  end if;

  select max(id) into v_latest
    from audit_log
   where entity = 'game' and entity_id = v_entry.entity_id
     and action in ('game.edit', 'game.delete', 'game.restore', 'game.undo');
  if v_latest is distinct from p_audit_id then
    raise exception 'something else has changed this game since'
      using errcode = 'STB07';
  end if;

  select * into v_game from games where id = v_entry.entity_id for update;

  if v_entry.action = 'game.edit' then
    if v_entry.before is null then
      raise exception 'that change has nothing to go back to'
        using errcode = 'STB07';
    end if;
    v_day := (v_entry.before->'game'->>'played_on')::date;
    -- Going back to the old day only works if nobody has played it since.
    if v_day is distinct from v_game.played_on
       and v_game.status = 'finished' and v_game.deleted_at is null then
      perform assert_day_free(v_day, v_game.id);
    end if;
    update games
       set played_on = v_day,
           season_id = ensure_season(v_day)
     where id = v_entry.entity_id;
    perform apply_game_results(v_entry.entity_id, v_entry.before->'players');

  elsif v_entry.action = 'game.delete' then
    -- Undoing a delete is a restore, under the same condition.
    if v_game.status = 'finished' then
      perform assert_day_free(v_game.played_on, v_game.id);
    end if;
    update games set deleted_at = null where id = v_entry.entity_id;

  elsif v_entry.action = 'game.restore' then
    update games set deleted_at = now() where id = v_entry.entity_id;

  else
    raise exception 'that kind of change cannot be undone'
      using errcode = 'STB07';
  end if;

  perform resettle_history();

  insert into audit_log (actor_player_id, action, entity, entity_id, after, note)
  values (p_actor, 'game.undo', 'game', v_entry.entity_id,
          game_snapshot(v_entry.entity_id),
          format('undid %s from %s', v_entry.action,
                 to_char(v_entry.at, 'YYYY-MM-DD HH24:MI')));
end
$fn$;

-- The forgotten Friday — as long as that Friday does not already have its
-- game. Today counts as taken while a game is still being played.
create or replace function add_manual_game(
  p_actor     uuid,
  p_played_on date,
  p_results   jsonb,
  p_note      text default null
) returns uuid language plpgsql volatile as $fn$
declare
  v_game_id uuid;
  v_season  uuid;
begin
  if p_played_on > stockholm_today() then
    raise exception 'that date has not happened yet' using errcode = 'STB06';
  end if;
  perform assert_day_free(p_played_on, null, true);

  v_season := ensure_season(p_played_on);

  insert into games (played_on, ruleset_id, season_id, status,
                     created_by, started_at, finished_at)
  select p_played_on, s.ruleset_id, s.id, 'finished', p_actor, now(), now()
    from seasons s where s.id = v_season
  returning id into v_game_id;

  perform apply_game_results(v_game_id, p_results);
  perform resettle_history();

  insert into audit_log (actor_player_id, action, entity, entity_id, after, note)
  values (p_actor, 'game.manual', 'game', v_game_id,
          game_snapshot(v_game_id), p_note);

  return v_game_id;
end
$fn$;

-- ===========================================================================
-- Everyone at a glance: each player's last five games
-- ===========================================================================

-- For the Players overview, which shows every player's recent form at once.
-- Read through PostgREST, a "last five per player" would have to fetch every
-- result and trim in the app — and api.max_rows (1000) would quietly cut the
-- oldest players' rows off once the history is long enough. Five per player
-- stays small for good.
create view player_recent_form with (security_invoker = true) as
select player_id, game_id, played_on, finish_position, participants,
       is_winner, is_shut_box
  from (
    select gr.*,
           row_number() over (
             partition by gr.player_id
             order by gr.played_on desc, gr.game_id desc
           ) as nth
      from game_results gr
  ) r
 where nth <= 5;

grant select on player_recent_form to service_role;

-- ---------------------------------------------------------------------------
-- Privileges (create or replace keeps them, but say so where it is read)
-- ---------------------------------------------------------------------------

do $grants$
declare
  v_fn text;
begin
  foreach v_fn in array array[
    'set_turn_result(uuid, uuid, uuid, smallint[], integer, integer)',
    'apply_game_results(uuid, jsonb)',
    'assert_day_free(date, uuid, boolean)',
    'start_game(uuid, uuid[])',
    'finish_game(uuid, uuid)',
    'edit_game(uuid, uuid, date, jsonb, text)',
    'restore_game(uuid, uuid)',
    'undo_game_change(uuid, bigint)',
    'add_manual_game(uuid, date, jsonb, text)'
  ]
  loop
    execute format('revoke execute on function %s from public, anon, authenticated', v_fn);
    execute format('grant execute on function %s to service_role', v_fn);
  end loop;
end
$grants$;


-- ===========================================================================
-- Migration history: every file in supabase/migrations, recorded as applied.
-- Earlier ones were applied by hand or by db push; the ones above just ran.
-- ===========================================================================
insert into supabase_migrations.schema_migrations (version, name)
values
  ('0001', 'tables'),
  ('0002', 'views'),
  ('0003', 'lock_12_tile'),
  ('0004', 'rulesets_seasons'),
  ('0005', 'game_lifecycle'),
  ('0006', 'audit_identity_audio'),
  ('0007', 'views'),
  ('0008', 'ratings'),
  ('0009', 'achievements'),
  ('0010', 'rpc_game_flow'),
  ('0011', 'realtime'),
  ('0012', 'finish_game_settles'),
  ('0013', 'game_management'),
  ('0014', 'plan_season'),
  ('0015', 'storage'),
  ('0016', 'safeupdate'),
  ('0017', 'roster'),
  ('0018', 'fika'),
  ('0019', 'cron'),
  ('0020', 'schedule'),
  ('0021', 'tournament'),
  ('0022', 'fika_avg_finish'),
  ('0023', 'one_counted_game_per_day')
on conflict (version) do nothing;

commit;
